#!/usr/bin/env bash
set -euo pipefail

cd "$HOME/Lumenarium"

manifest="${SCENELM_MANIFEST:-/tmp/scenelm_smoke1.txt}"
reference="${SCENELM_REFERENCE_VERSION:-v4_scenelm_adam400_control}"
candidate="${SCENELM_VERSION:-v4_scenelm_v1}"
reference_logs="${SCENELM_REFERENCE_LOG_ROOT:-logs/${reference}}"
candidate_logs="${SCENELM_LOG_ROOT:-logs/${candidate}}"
lm_iterations="${SCENELM_MAX_ITERATIONS:-30}"
scenelm_solver="${SCENELM_SOLVER:-scenelm}"
gpu_floor="${IMAGINARIUM_GPU_FREE_FLOOR_MB:-16000}"

echo "===== START Adam400 control $(date) ====="
env \
  IMAGINARIUM_PAPER30_MANIFEST="$manifest" \
  IMAGINARIUM_S4_SOURCE_VERSION=v4_deepsearch \
  IMAGINARIUM_S4_SOURCE_STAGE=S3_pose_inference \
  IMAGINARIUM_S4_SOURCE_PATTERN="*_placement_info.json" \
  IMAGINARIUM_S4_TARGET_VERSION="$reference" \
  IMAGINARIUM_S4_ENGINE=layoutvlm \
  IMAGINARIUM_LAYOUTVLM_STAGE=full \
  IMAGINARIUM_LAYOUTVLM_SOLVER=adam \
  IMAGINARIUM_LAYOUTVLM_ITERATIONS=400 \
  IMAGINARIUM_LAYOUTVLM_ACTIVE_SET_ROUTER=0 \
  IMAGINARIUM_GPU_FREE_FLOOR_MB="$gpu_floor" \
  IMAGINARIUM_S4_SCENE_TIMEOUT=3600 \
  IMAGINARIUM_S4_WORKER_LOG_ROOT="$reference_logs" \
  bash scripts/run_paper30_v4_s4_only_dual_gpu.sh

echo "===== START SceneLM candidate $(date) ====="
env \
  IMAGINARIUM_PAPER30_MANIFEST="$manifest" \
  IMAGINARIUM_S4_SOURCE_VERSION=v4_deepsearch \
  IMAGINARIUM_S4_SOURCE_STAGE=S3_pose_inference \
  IMAGINARIUM_S4_SOURCE_PATTERN="*_placement_info.json" \
  IMAGINARIUM_S4_TARGET_VERSION="$candidate" \
  IMAGINARIUM_S4_ENGINE=layoutvlm \
  IMAGINARIUM_LAYOUTVLM_STAGE=full \
  IMAGINARIUM_LAYOUTVLM_SOLVER="$scenelm_solver" \
  IMAGINARIUM_LAYOUTVLM_ITERATIONS="$lm_iterations" \
  IMAGINARIUM_LAYOUTVLM_ACTIVE_SET_ROUTER=0 \
  IMAGINARIUM_SCENELM_INITIAL_DAMPING="${IMAGINARIUM_SCENELM_INITIAL_DAMPING:-0.01}" \
  IMAGINARIUM_SCENELM_PCG_ITERATIONS="${IMAGINARIUM_SCENELM_PCG_ITERATIONS:-12}" \
  IMAGINARIUM_SCENELM_PCG_TOLERANCE="${IMAGINARIUM_SCENELM_PCG_TOLERANCE:-0.001}" \
  IMAGINARIUM_SCENELM_ACCEPTANCE_THRESHOLD="${IMAGINARIUM_SCENELM_ACCEPTANCE_THRESHOLD:-0.1}" \
  IMAGINARIUM_SCENELM_GRADIENT_TOLERANCE="${IMAGINARIUM_SCENELM_GRADIENT_TOLERANCE:-0.00001}" \
  IMAGINARIUM_SCENELM_RELATIVE_ENERGY_TOLERANCE="${IMAGINARIUM_SCENELM_RELATIVE_ENERGY_TOLERANCE:-0.0001}" \
  IMAGINARIUM_SCENELM_PATIENCE="${IMAGINARIUM_SCENELM_PATIENCE:-3}" \
  IMAGINARIUM_SCENELM_MAX_TRANSLATION_STEP="${IMAGINARIUM_SCENELM_MAX_TRANSLATION_STEP:-0.2}" \
  IMAGINARIUM_SCENELM_MAX_YAW_STEP_DEG="${IMAGINARIUM_SCENELM_MAX_YAW_STEP_DEG:-15}" \
  IMAGINARIUM_GPU_FREE_FLOOR_MB="$gpu_floor" \
  IMAGINARIUM_S4_SCENE_TIMEOUT=3600 \
  IMAGINARIUM_S4_WORKER_LOG_ROOT="$candidate_logs" \
  bash scripts/run_paper30_v4_s4_only_dual_gpu.sh

echo "SCENELM_PAIRED_FINISHED reference=$reference candidate=$candidate solver=$scenelm_solver $(date)"
