#!/usr/bin/env bash
set -euo pipefail

cd "$HOME/Lumenarium"

manifest="${SCENEBA_ACTIVE_ROUTER_MANIFEST:-/tmp/sceneba_compute_smoke5.txt}"
target="${SCENEBA_ACTIVE_ROUTER_VERSION:-v4_active_router_v1}"
log_root="${SCENEBA_ACTIVE_ROUTER_LOG_ROOT:-logs/sceneba_active_router_v1_smoke5}"

env \
  IMAGINARIUM_PAPER30_MANIFEST="$manifest" \
  IMAGINARIUM_S4_SOURCE_VERSION=v4_deepsearch \
  IMAGINARIUM_S4_SOURCE_STAGE=S3_pose_inference \
  IMAGINARIUM_S4_SOURCE_PATTERN="*_placement_info.json" \
  IMAGINARIUM_S4_TARGET_VERSION="$target" \
  IMAGINARIUM_S4_ENGINE=layoutvlm \
  IMAGINARIUM_LAYOUTVLM_STAGE=full \
  IMAGINARIUM_LAYOUTVLM_ITERATIONS=400 \
  IMAGINARIUM_LAYOUTVLM_ACTIVE_SET_ROUTER=1 \
  IMAGINARIUM_LAYOUTVLM_ROUTER_CHECKPOINTS=30,100 \
  IMAGINARIUM_LAYOUTVLM_ROUTER_HIGH_DEGREE="${IMAGINARIUM_LAYOUTVLM_ROUTER_HIGH_DEGREE:-6}" \
  IMAGINARIUM_LAYOUTVLM_ROUTER_WAKE_MULTIPLIER="${IMAGINARIUM_LAYOUTVLM_ROUTER_WAKE_MULTIPLIER:-1.5}" \
  IMAGINARIUM_GPU_FREE_FLOOR_MB="${IMAGINARIUM_GPU_FREE_FLOOR_MB:-16000}" \
  IMAGINARIUM_S4_SCENE_TIMEOUT="${IMAGINARIUM_S4_SCENE_TIMEOUT:-3600}" \
  IMAGINARIUM_S4_WORKER_LOG_ROOT="$log_root" \
  bash scripts/run_paper30_v4_s4_only_dual_gpu.sh
