#!/usr/bin/env bash
set -euo pipefail

cd "$HOME/Lumenarium"
manifest="${SCENEPROOF_PLANE_CHART_MANIFEST:-/tmp/sceneproof_plane_chart_smoke1.txt}"
version="${SCENEPROOF_PLANE_CHART_VERSION:-v5_sceneproof_assignment_compensated_joint_tangent_smoke1_fix52}"

printf '%s\n' bedroom_01 > "$manifest"

env \
  IMAGINARIUM_PAPER30_MANIFEST="$manifest" \
  IMAGINARIUM_S4_SOURCE_VERSION=v4_deepsearch \
  IMAGINARIUM_S4_SOURCE_STAGE=S3_pose_inference \
  IMAGINARIUM_S4_SOURCE_PATTERN='*_placement_info.json' \
  IMAGINARIUM_S4_TARGET_VERSION="$version" \
  IMAGINARIUM_S4_ENGINE=layoutvlm \
  IMAGINARIUM_LAYOUTVLM_STAGE=full \
  IMAGINARIUM_LAYOUTVLM_SOLVER=v5_scenelm \
  IMAGINARIUM_LAYOUTVLM_ITERATIONS=2 \
  IMAGINARIUM_LAYOUTVLM_ACTIVE_SET_ROUTER=0 \
  IMAGINARIUM_SCENEPROOF_PROGRAM_IR=1 \
  IMAGINARIUM_SCENEPROOF_REQUIRE_FACTOR_PARITY=1 \
  IMAGINARIUM_SCENEPROOF_REQUIRE_BINDING_AUDIT=1 \
  IMAGINARIUM_SCENEPROOF_SHADOW_JACOBIAN_OWNERSHIP=1 \
  IMAGINARIUM_SCENEPROOF_STABLE_LINEARIZATIONS=2 \
  IMAGINARIUM_SCENEPROOF_FULL_SO3_GUARDED_SCHUR=1 \
  IMAGINARIUM_SCENEPROOF_WARM_START_ANCHORED_PLANE_TRANSLATION=1 \
  IMAGINARIUM_SCENEPROOF_PLANE_ANCHOR_NORMAL_LIMIT_M=0.02 \
  IMAGINARIUM_SCENEPROOF_PLANE_PROXY_ABSTAIN_GAP_M=0.02 \
  IMAGINARIUM_SCENEPROOF_PLANE_ATTACH_REQUIRES_WITNESS=1 \
  IMAGINARIUM_SCENEPROOF_MATERIALIZED_WARM_START=1 \
  IMAGINARIUM_SCENEPROOF_PLANE_SIBLING_TANGENT_PROJECTION=1 \
  IMAGINARIUM_SCENEPROOF_PLANE_SIBLING_MAX_SHIFT_M=0.35 \
  IMAGINARIUM_SCENEPROOF_PLANE_COMPONENT_IMAGE_GAUGE=0 \
  IMAGINARIUM_SCENEPROOF_MESH_VISIBILITY_AUDIT=1 \
  IMAGINARIUM_SCENEPROOF_VISIBILITY_RESOLUTION=256 \
  IMAGINARIUM_SCENEPROOF_VISIBILITY_MIN_PIXELS=64 \
  IMAGINARIUM_SCENEPROOF_VISIBLE_SIDE_CANDIDATE_AUDIT=0 \
  IMAGINARIUM_SCENEPROOF_TANGENT_CANDIDATE_AUDIT=1 \
  IMAGINARIUM_SCENEPROOF_JOINT_TANGENT_CANDIDATE_AUDIT=1 \
  IMAGINARIUM_SCENEPROOF_TANGENT_MAX_SHIFT_M=0.35 \
  IMAGINARIUM_SCENEPROOF_VISIBLE_SIDE_CLEARANCE_M=0.002 \
  IMAGINARIUM_SCENEPROOF_VISIBLE_SIDE_MAX_SHIFT_M=0.15 \
  IMAGINARIUM_SCENEPROOF_VISIBLE_SIDE_ATTACHMENT_TOLERANCE_M=0.005 \
  IMAGINARIUM_SCENEPROOF_VISIBILITY_NOHARM_TOLERANCE=0.005 \
  IMAGINARIUM_SCENEPROOF_VISIBLE_SIDE_MIN_RECALL_GAIN=0.05 \
  IMAGINARIUM_SCENELM_KINEMATIC_BACKSUB=0 \
  IMAGINARIUM_GPU_FREE_FLOOR_MB="${IMAGINARIUM_GPU_FREE_FLOOR_MB:-16000}" \
  IMAGINARIUM_S4_SCENE_TIMEOUT=3600 \
  IMAGINARIUM_S4_WORKER_LOG_ROOT="logs/${version}" \
  bash scripts/run_paper30_v4_s4_only_dual_gpu.sh
